---
# defaults file for rh-console-imagebuilder
imagebuilder_custom_filesystem: []
imagebuilder_architecture: x86_64
imagebuilder_dest_folder: /tmp
imagebuilder_download_file: false
imagebuilder_distribution: rhel-9
imagebuilder_image_packages: []
imagebuilder_force_create: false
imagebuilder_insights_enabled: true
imagebuilder_rhc_enabled: true
imagebuilder_subscription: {}
imagebuilder_retries: 10
